### ISSUE TITLE
EADDRINUSE error

### ISSUE THREAD

**Issue by antarasi** [avoidwork/tiny-worker#11]
I'm unable tu run Hello World example because of the following error

```
Error: listen EADDRINUSE :::63541
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Agent.Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Agent.Server.listen (net.js:1366:5)
    at Object.start (_debug_agent.js:21:9)
    at startup (node.js:70:9)
    at node.js:963:3
Error: listen EADDRINUSE :::63541
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Agent.Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Agent.Server.listen (net.js:1366:5)
    at Object.start (_debug_agent.js:21:9)
    at startup (node.js:70:9)
    at node.js:963:3
Error: listen EADDRINUSE :::63541
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Agent.Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Agent.Server.listen (net.js:1366:5)
    at Object.start (_debug_agent.js:21:9)
    at startup (node.js:70:9)
    at node.js:963:3
```

**Comment by antarasi** [comment]
Seems to be an issue related to debugger. 
Check out this comment:
https://github.com/nodejs/node/issues/3469#issuecomment-149961323

**Comment by avoidwork** [comment]
Hi,

Yes, it is. This appears to be a reoccurring problem for people trying to debug child process. The module currently doesn't support any customization because that is not available to a real `Worker`, but I'll probably be changing it to accept more args.

**Comment by antarasi** [comment]
I think that execArgv checking of parent thread will solve this issue. The problem occurs only because both processes are using the debugger on the same port. If we can detect that we have debug argument in parent/main thread then we can pass `port+1`, othrewise it is not necessary to pass any arguments. As a result your module will be able to run on production as well as on development (debug) environment.

**Comment by avoidwork** [comment]
I don't think that'll work; usually people null the inputs to avoid inheritance. Solving the problem for 1 use case usually breaks others, so I'll likely just expose and put the onus on the developer to handle their situation.

**Comment by antarasi** [comment]
I have another idea. All forked node processes inherit execArgv from parent thread but it isn't desired behavior because the port is already bound.   
Here is an example that shows how this situation can be avoided:
```
const worker = require('child_process').fork(
    __dirname + '/worker',
    [],
    { execArgv: [] }
  );
```

Additionaly you can detect if adding these parameters is needed by determining if we are in debug mode:
```
var debug = typeof v8debug === 'object';
```

**Comment by avoidwork** [comment]
Fixed with 2.0.0: https://github.com/avoidwork/tiny-worker/releases/tag/2.0.0

**Comment by avoidwork** [comment]
Hi,

So 2.0.1 might be required depending on your version of node; the constructor now takes the `args` & `options` for `child_process.fork()` which allows you to specify the env variables.

**Comment by antarasi** [comment]
Great. Thanks for update!
